### ISSUE TITLE
The pre train model can not open

### ISSUE THREAD

**Issue by JosephineRabbit** [namedBen/Convolutional-Pose-Machines-Pytorch#2]
hi , thanks for share your model. I downlaoded it but met a problem like this:
tar -xvf cpm_latest.pth.tar
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

Is it be compressed properly?

**Comment by namedBen** [comment]
actually, the file "cpm_latest.pth.tar" is the model that stores parameters.you don't have to unzip it.
You can use the command "torch.load( the path of cpm_latest.pth.tar )" to load parameters.

**Comment by JosephineRabbit** [comment]
..my fault^_^ 
THs!
